### ISSUE TITLE
Data todo list

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gftrends#1]
- [ ] outside yelloweye?
- [ ] 2 stocks from Andy
- [ ] get USR and MSY and MCMC samples in for pcod
- [ ] stitch on quillback after mcmc processing
- [ ] get walleye USR (and MSY?) from Rowan
- [ ]  inside yelloweye MCMC and USR and MSY - me
- [ ] pull in survey data
