### ISSUE TITLE
Modelling todo list

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gftrends#2]
- [x] clean up data processing / fitting / extracting code
- [x] fit by B/LRP, B/USR, B/MSY
- [ ] try jackknifing out species
- [ ] try doing by 'major' survey index stocks anchored in 2002/2003
